export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_ERROR = "DELETE_PROJECT_ERROR";
